kind: Service
apiVersion: v1
metadata:
  name:  ct-dummy-lb
  namespace: ct-dummy-argo
  labels:
    role: web
    dns: route53
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: name=ct-dummy-dev, terraform=false
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: ct-dummy
  type:  LoadBalancer
  ports:
  - name:  ui
    port:  80
    targetPort:  8000