# on:
#   push:
#     branches: master

# jobs:
#   build-docker:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: Generate semver
#       id: version-generator
#       run: |
#         ARTEFACT_VERSION=$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/") 
#         echo '::set-output name=ARTEFACT_VERSION::$(git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/")'

#     - name: Build image
#       run: |
#         docker build --build-arg Build=${{ steps.version-generator.outputs.ARTEFACT_VERSION }} \
#         -t klimdos/python-flask-dummy:${{ steps.version-generator.outputs.ARTEFACT_VERSION }} .
#         docker tag klimdos/python-flask-dummy:${{ steps.version-generator.outputs.ARTEFACT_VERSION }} \
#         klimdos/python-flask-dummy:latest

#     - name: Push image
#       run: |
#         docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
#         docker push klimdos/python-flask-dummy:${{ steps.version-generator.outputs.ARTEFACT_VERSION }}
