on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          #tags: klimdos/dummy-flask-app:latest
          tags: ${{ secrets.GITHUB_REPOSITORY }}:${{ secrets.GITHUB_SHA }}
          # build-args: |
          #   arg1=value1
          #   arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


    


---
name: Python Linting
on: [pull_request]
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install pylint pylint-fail-under

      - name: run pylint
        run: |
            echo ${{steps.changed_files.outputs.added_modified}}
            for changed_file in ${{ steps.changed_files.outputs.added_modified }}; do
              if [[ $changed_file =~ ".py" ]]; then
                  pylint-fail-under --fail_under 7.0 ${changed_file}
              fi
            done