on:
  push:
    branches: master

jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
       ARTEFACT_VERSION: 1.0
    steps:

    - name: Set selected color
      run: echo '::set-output name=SELECTED_COLOR::green'
      id: random-color-generator

    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

    - uses: actions/checkout@v1
    - name: Generate semver
      run: |
        git describe --long --always | sed -r "s/-(([^-]*-){1}[^-]*)$/.\\1/"
    - name: Build image
      run: |
        docker build --build-arg Build=${GITHUB_SHA} -t klimdos/python-flask-dummy:${GITHUB_SHA} .
        docker tag klimdos/python-flask-dummy:${GITHUB_SHA} klimdos/python-flask-dummy:latest
    - name: Push docker image (hash)
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push klimdos/python-flask-dummy:${GITHUB_SHA}


        <job_id>.steps.env


