---
name: Python Linting
on: [push, pull_request]
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8


      - name: Run linters
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # - uses: actions/checkout@v1
      # - uses: actions/python-lint@v1.1.0
      #     with:
      #       use-pylint: true
      - name: Run linters
        uses: ricardochaves/python-lint@v1.1.0
        with:
          use-pylint: true
