---
name: Python Linting
on: [pull_request]
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Check branch name
        run: |
          echo ${{ github.ref_name }}

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install pylint pylint-fail-under

      - name: run pylint
        run: |
            echo ${{steps.changed_files.outputs.added_modified}}
            for changed_file in ${{ steps.changed_files.outputs.added_modified }}; do
              if [[ $changed_file =~ ".py" ]]; then
                  pylint-fail-under --fail_under 7.0 ${changed_file}
              fi
            done
