---
name: Python Linting
on: [push, pull_request]
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1
        run: |
            for changed_file in ${{ steps.files.outputs.all }}; do
              echo "Do something with this ${changed_file}."
              if [[ $changed_file =~ ".py" ]]; then
                  echo "python ${changed_file}"
              fi
            done

        #with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          #format: ''


      # - name: Changed Files Exporter
      #   id: changed_files
      #   uses: futuratrepadeira/changed-files@v3.1.0
      #   with:
      #     repo-token: ${{ github.token }}

      - name: debug
        run: echo ${{steps.changed_files.outputs.added_modified}}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8 pylint

      # - name: Run linters
      #   uses: samuelmeuli/lint-action@v1
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     # Enable linters
      #     black: true
      #     flake8: true

      - name: run pylint
        run: pylint *.py